# Generated by Django 5.2.6 on 2025-09-30 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VagaEmprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vagas/', verbose_name='Foto')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
            ],
            options={
                'verbose_name': 'Vaga de Emprego',
                'verbose_name_plural': 'Vagas de Emprego',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
